# Base docker-compose file. Use docker-compose.override.yml files as needed.

services:
  sensors:
    build:
      context: .
    env_file:
      - env/django.env
    entrypoint: /opt/app/docker-entrypoint.sh
    command: gunicorn -c /opt/app/webapp/gunicorn.conf.py sensorplaces.wsgi
    # command: python manage.py runserver 0.0.0.0:8010
    restart: unless-stopped
    ports:
      - 8002:8002
    volumes:
      - sensors-db:/opt/app/db
      - sensors-static:/opt/app/static_files
      - sensors-media:/opt/app/media
      # - ./webapp:/opt/app/webapp
volumes:
  sensors-db:
  sensors-static:
  sensors-media:

networks:
  default:
    name: webhost
    external: true