# Generated by Django 6.0 on 2025-12-15 14:41

import django.db.models.deletion
import django.db.models.functions.text
import sensors.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='bi-hdd', help_text='Bootstrap icon class (e.g., bi-hdd, bi-router)', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '6. Device Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InfluxStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(help_text='URL to InfluxDB instance')),
                ('org', models.CharField(help_text='InfluxDB organization', max_length=100)),
                ('bucket_name', models.CharField(max_length=100)),
                ('token', models.CharField(help_text='InfluxDB API token', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('x_pos', models.DecimalField(blank=True, decimal_places=2, default=Decimal('50.00'), max_digits=5, null=True)),
                ('y_pos', models.DecimalField(blank=True, decimal_places=2, default=Decimal('50.00'), max_digits=5, null=True)),
                ('z_pos', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '2. Locations',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('graph_type', models.CharField(blank=True, choices=[('LINE', 'Line Graph'), ('SCATTER', 'Scatter Plot'), ('BAR', 'Bar Graph'), ('STEP', 'Step Graph')], default='LINE', max_length=20, null=True)),
                ('decimal_places', models.PositiveIntegerField(blank=True, default=2, null=True)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('allow_override', models.BooleanField(default=False)),
                ('default_stale_threshold_seconds', models.PositiveIntegerField(blank=True, default=300, help_text='Default stale time for this sensor type, in seconds. Default is 5 minutes.', null=True)),
            ],
            options={
                'verbose_name_plural': '7. Sensor Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TimeStampedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('symbol', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Units',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('device_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes for this device.', null=True)),
                ('scraped_data', models.JSONField(blank=True, default=dict, help_text='Additional device-specific data collected from webhooks or APIs.')),
                ('is_lorawan', models.BooleanField(default=False, verbose_name='LoRaWAN Device')),
                ('is_switchbot', models.BooleanField(default=False, help_text='Is this a SwitchBot device?')),
                ('hub_id', models.CharField(blank=True, help_text='Identifier for the hub or bridge device, if any.', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='inactive devices will be hidden by default')),
                ('scrape_data', models.BooleanField(default=False, help_text='Set to true to capture the next full data payload from the device.')),
                ('last_seen', models.DateTimeField(blank=True, help_text='Last time a webhook was received from this device.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='sensors.devicetype')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='sensors.location')),
            ],
            options={
                'verbose_name_plural': '3. Devices',
                'ordering': ['location__place', 'location', '-is_active', django.db.models.functions.text.Lower('name')],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('is_active', models.BooleanField(default=True)),
                ('siteplan_image', models.ImageField(blank=True, null=True, upload_to='siteplan_images/', validators=[sensors.models.validate_image_size])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('switchbot_enable', models.BooleanField(default=False, help_text='Enable SwitchBot integration for this place.')),
                ('switchbot_token', models.CharField(blank=True, max_length=255, null=True)),
                ('switchbot_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('switchbot_user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('default_influx_store', models.ForeignKey(blank=True, help_text="Default InfluxDB store for this place's sensors.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_places', to='sensors.influxstore')),
                ('switchbot_influx_store', models.ForeignKey(blank=True, help_text='InfluxDB store specifically for SwitchBot devices at this place.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='switchbot_for_places', to='sensors.influxstore')),
            ],
            options={
                'verbose_name_plural': '1. Places',
                'ordering': ['-is_active', django.db.models.functions.text.Lower('name')],
            },
        ),
        migrations.AddField(
            model_name='location',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='sensors.place'),
        ),
        migrations.AddField(
            model_name='influxstore',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='influx_stores', to='sensors.place'),
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('switchbot_sensor_name', models.CharField(blank=True, help_text='Original sensor name from SwitchBot API', max_length=100, null=True)),
                ('unit_override', models.BooleanField(default=False)),
                ('data_store', models.CharField(blank=True, choices=[('DIRECT', 'Direct'), ('INFLUX', 'InfluxDB (Gauge)'), ('INFLUX_CUMULATIVE_RESET', 'InfluxDB (Cumulative, Resets)'), ('NONE', 'None')], default='NONE', max_length=30, null=True, verbose_name='Data Store')),
                ('graph_type', models.CharField(blank=True, choices=[('LINE', 'Line Graph'), ('SCATTER', 'Scatter Plot'), ('BAR', 'Bar Graph'), ('STEP', 'Step Graph')], default=None, max_length=20, null=True)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('min_value_override', models.BooleanField(default=False)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('max_value_override', models.BooleanField(default=False)),
                ('influx_measurement', models.CharField(blank=True, max_length=100, null=True)),
                ('influx_field_name', models.CharField(blank=True, help_text="The field name in InfluxDB, e.g., 'value' or 'temperature'", max_length=100, null=True)),
                ('influx_tag_key', models.CharField(blank=True, help_text="The key of the tag used to identify this sensor's data, e.g., 'sensor_id'", max_length=100, null=True)),
                ('cached_reading_value', models.FloatField(blank=True, editable=False, null=True)),
                ('cached_reading_timestamp', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_cached_timestamp', models.DateTimeField(blank=True, editable=False, null=True)),
                ('cached_reading_source', models.CharField(blank=True, editable=False, max_length=50, null=True)),
                ('stale_threshold_seconds', models.PositiveIntegerField(blank=True, help_text='Override the default stale threshold for this sensor (in seconds).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='sensors.device')),
                ('influx_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensors', to='sensors.influxstore')),
                ('sensor_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sensors.sensortype')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sensors.unit')),
            ],
            options={
                'verbose_name_plural': '4. Sensors',
                'ordering': [django.db.models.functions.text.Lower('device__location__name'), django.db.models.functions.text.Lower('device__name'), '-is_active', django.db.models.functions.text.Lower('name')],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('value_boolean', models.BooleanField(blank=True, help_text='Boolean value for this reading, if applicable.', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='sensors.sensor')),
            ],
            options={
                'verbose_name_plural': '5. Sensor Readings',
            },
        ),
        migrations.CreateModel(
            name='ToastNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('info', 'Info'), ('danger', 'Danger')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toast_notifications', to='sensors.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toast_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ToastReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('toast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.toastnotification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sensortype',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sensors.unit'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('place', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='influxstore',
            unique_together={('place', 'name')},
        ),
        migrations.AddIndex(
            model_name='toastnotification',
            index=models.Index(fields=['user', '-created_at'], name='sensors_toa_user_id_0b5407_idx'),
        ),
        migrations.AddIndex(
            model_name='toastnotification',
            index=models.Index(fields=['place', '-created_at'], name='sensors_toa_place_i_e13562_idx'),
        ),
        migrations.AddIndex(
            model_name='toastnotification',
            index=models.Index(fields=['user', 'place', '-created_at'], name='sensors_toa_user_id_2fd531_idx'),
        ),
        migrations.AddIndex(
            model_name='toastreadstatus',
            index=models.Index(fields=['user', 'toast'], name='sensors_toa_user_id_a6864d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='toastreadstatus',
            unique_together={('user', 'toast')},
        ),
    ]
