# Generated by Django 4.2.19 on 2025-02-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='address',
        ),
        migrations.RemoveField(
            model_name='location',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='longitude',
        ),
        migrations.AddField(
            model_name='place',
            name='latitude',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=9), # type: ignore
        ),
        migrations.AddField(
            model_name='place',
            name='longitude',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=9), # type: ignore
        ),
    ]
