# Generated by Django 6.0 on 2025-12-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_seed_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetype',
            name='aliases',
            field=models.JSONField(blank=True, default=list, help_text='List of alternative names that map to this device type (for auto-matching)'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='is_system',
            field=models.BooleanField(default=False, help_text='System records (pk < 100) are immutable and cannot be edited'),
        ),
        migrations.AlterField(
            model_name='sensortype',
            name='aliases',
            field=models.JSONField(blank=True, default=list, help_text='List of alternative names that map to this sensor type (for auto-matching)'),
        ),
        migrations.AlterField(
            model_name='sensortype',
            name='is_system',
            field=models.BooleanField(default=False, help_text='System records (pk < 100) are immutable and cannot be edited'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='is_system',
            field=models.BooleanField(default=False, help_text='System records (pk < 100) are immutable and cannot be edited'),
        ),
    ]
