# Generated by Django 6.0 on 2025-12-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_alter_devicetype_aliases_alter_devicetype_is_system_and_more'),
    ]

    operations = [
        # Rename switchbot_sensor_name to reading_key (preserves existing data)
        migrations.RenameField(
            model_name='sensor',
            old_name='switchbot_sensor_name',
            new_name='reading_key',
        ),
        # Update the field definition after rename
        migrations.AlterField(
            model_name='sensor',
            name='reading_key',
            field=models.CharField(blank=True, help_text='Key used to match inbound readings from webhooks/APIs', max_length=100, null=True),
        ),
        # Add InfluxDB configuration fields to SensorType
        migrations.AddField(
            model_name='sensortype',
            name='influx_field_name',
            field=models.CharField(blank=True, help_text="InfluxDB field name, e.g., 'temperature', 'humidity'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sensortype',
            name='influx_measurement',
            field=models.CharField(blank=True, help_text="InfluxDB measurement name, e.g., 'climate', 'powermon'", max_length=100, null=True),
        ),
    ]
