# Generated by Django 4.2.19 on 2025-02-25 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_alter_device_serial_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfluxSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('server_dns', models.CharField(max_length=255)),
                ('server_port', models.IntegerField(default=8086)),
                ('bucket_name', models.CharField(max_length=100)),
                ('org', models.CharField(max_length=100)),
                ('read_token', models.CharField(max_length=255)),
                ('write_token', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'InfluxDB Sources',
            },
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name_plural': '3. Devices'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name_plural': '2. Locations'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name_plural': '1. Places'},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'verbose_name_plural': '4. Sensors'},
        ),
        migrations.AlterModelOptions(
            name='sensorreading',
            options={'verbose_name_plural': '5. Sensor Readings'},
        ),
        migrations.AddField(
            model_name='sensor',
            name='data_type',
            field=models.CharField(choices=[('DB', 'Database'), ('INFLUX', 'InfluxDB')], default='DB', max_length=10),
        ),
        migrations.AddField(
            model_name='sensor',
            name='influx_measurement',
            field=models.CharField(blank=True, default='sensor_readings', max_length=100),
        ),
        migrations.AddField(
            model_name='sensor',
            name='influx_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensors', to='sensors.influxsource'),
        ),
    ]
