# Generated by Django 6.0 on 2025-12-17 10:22

from django.db import migrations


# Data from INFLUX_GROUP_MAP in measurement_utils.py
INFLUX_GROUP_MAP = {
    # Climate
    'Temperature': ('climate', 'temperature'),
    'Humidity': ('climate', 'humidity'),
    'Light Level': ('climate', 'light_level'),
    'Ambient Light': ('climate', 'light_level'),  # Alias for Light Level

    # Power
    'Power': ('powermon', 'power'),
    'Current': ('powermon', 'current'),
    'Voltage': ('voltage', 'voltage'),

    # Battery
    'Battery Level': ('battery', 'percent'),
    'Battery Voltage': ('battery', 'voltage'),

    # Environmental
    'Water Detector': ('flood', 'flood'),
    'Leak Detected': ('flood', 'flood'),
    'PM2.5': ('air_quality', 'pm25'),

    # Motion
    'Motion': ('motion', 'detected'),

    # Switch
    'Switch': ('switch', 'state'),
}


def populate_influx_fields(apps, schema_editor):
    """Populate SensorType influx fields from the INFLUX_GROUP_MAP."""
    SensorType = apps.get_model('sensors', 'SensorType')

    for sensor_type in SensorType.objects.all():
        if sensor_type.name in INFLUX_GROUP_MAP:
            measurement, field = INFLUX_GROUP_MAP[sensor_type.name]
            sensor_type.influx_measurement = measurement
            sensor_type.influx_field_name = field
            sensor_type.save(update_fields=['influx_measurement', 'influx_field_name'])


def reverse_populate(apps, schema_editor):
    """Reverse: clear influx fields."""
    SensorType = apps.get_model('sensors', 'SensorType')
    SensorType.objects.all().update(influx_measurement=None, influx_field_name=None)


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_add_influx_fields_to_sensortype'),
    ]

    operations = [
        migrations.RunPython(populate_influx_fields, reverse_populate),
    ]
