# Generated by Django 6.0 on 2025-12-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_populate_sensortype_influx_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensortype',
            name='display_name',
            field=models.CharField(blank=True, help_text='Friendly name for sensors (defaults to name if blank)', max_length=50),
        ),
    ]
