# Generated by Django 5.1.6 on 2025-02-26 14:31

import django.core.validators
import sensors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0006_location_x_coord_location_y_coord_place_site_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='site_plan',
            field=models.ImageField(blank=True, help_text='Upload a site plan image (JPG/PNG, minimum 1024x768, max 5MB)', null=True, upload_to='site_plans/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png']), sensors.models.validate_image_size]),
        ),
    ]
