# Generated by Django 5.1.6 on 2025-02-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0008_location_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive locations will be hidden by default'),
        ),
    ]
