# Generated by Django 5.1.6 on 2025-02-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0009_alter_location_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.DecimalField(decimal_places=5, help_text='Latitude in decimal degrees (±90.00000)', max_digits=8),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.DecimalField(decimal_places=5, help_text='Longitude in decimal degrees (±180.00000)', max_digits=8),
        ),
    ]
