# Generated by Django 5.1.6 on 2025-02-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0010_alter_place_latitude_alter_place_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive places will be hidden by default'),
        ),
        migrations.AlterField(
            model_name='device',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive devices will be hidden by default'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive sensors will be hidden by default'),
        ),
    ]
