# Generated by Django 5.1.6 on 2025-02-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0011_place_is_active_alter_device_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
