# Generated by Django 5.1.6 on 2025-02-27 16:19

import django.db.models.deletion
from django.db import migrations, models

def remove_existing_sensors(apps, schema_editor):
    Sensor = apps.get_model('sensors', 'Sensor')
    # Remove all existing sensors
    Sensor.objects.all().delete()

def create_default_device_type(apps, schema_editor):
    DeviceType = apps.get_model('sensors', 'DeviceType')
    # Create the default "Other" device type
    other_type = DeviceType.objects.create(
        name='Other',
        description='Default device type for existing devices',
        icon='bi-device-hdd',
        is_active=True
    )
    
    # Update all existing devices to use this device type
    Device = apps.get_model('sensors', 'Device')
    Device.objects.all().update(device_type_new_id=other_type.id)

def reverse_device_type_migration(apps, schema_editor):
    DeviceType = apps.get_model('sensors', 'DeviceType')
    DeviceType.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0012_place_slug'),
    ]

    operations = [
        # First remove all sensors since they depend on devices
        migrations.RunPython(
            remove_existing_sensors,
            reverse_code=migrations.RunPython.noop
        ),
        
        # Create the DeviceType model
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='bi-hdd', help_text='Bootstrap icon class (e.g., bi-hdd, bi-router)', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '3. Device Types',
                'ordering': ['name'],
            },
        ),
        
        # Update Device model options
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name_plural': '4. Devices'},
        ),
        
        # Add temporary nullable field
        migrations.AddField(
            model_name='device',
            name='device_type_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='sensors.devicetype'),
        ),
        
        # Create default device type and update existing devices
        migrations.RunPython(
            create_default_device_type,
            reverse_code=reverse_device_type_migration
        ),
        
        # Make the field required
        migrations.AlterField(
            model_name='device',
            name='device_type_new',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='sensors.devicetype', null=True),
        ),
        
        # Remove the old field
        migrations.RemoveField(
            model_name='device',
            name='device_type',
        ),
        
        # Rename the new field
        migrations.RenameField(
            model_name='device',
            old_name='device_type_new',
            new_name='device_type',
        ),
    ]

