# Generated by Django 5.1.6 on 2025-02-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0014_add_device_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='manufacturer',
            field=models.CharField(blank=True, help_text='Device manufacturer', max_length=50),
        ),
        migrations.AddField(
            model_name='device',
            name='model',
            field=models.CharField(blank=True, help_text='Device model number or name', max_length=50),
        ),
    ]
