# Generated by Django 5.1.6 on 2025-02-27 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0017_add_site_plan_layout_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='place',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
