# Generated by Django 5.1.6 on 2025-02-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0018_alter_place_address_alter_place_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensor',
            options={'ordering': ['name'], 'verbose_name_plural': '5. Sensors'},
        ),
        migrations.AddField(
            model_name='sensor',
            name='unit',
            field=models.CharField(choices=[('°C', 'Celsius'), ('°F', 'Fahrenheit'), ('%', 'Percent'), ('hPa', 'Hectopascal'), ('ppm', 'Parts per Million'), ('other', 'Other')], default='other', max_length=10),
        ),
    ]
