# Generated by Django 5.1.6 on 2025-03-06 03:28

import django.db.models.functions.text
import sensors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0019_alter_sensor_options_sensor_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['location', '-is_active', django.db.models.functions.text.Lower('name')], 'verbose_name_plural': '4. Devices'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-is_active', 'name'], 'verbose_name_plural': '2. Locations'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['-is_active', django.db.models.functions.text.Lower('name')], 'verbose_name_plural': '1. Places'},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'ordering': [django.db.models.functions.text.Lower('device__location__name'), django.db.models.functions.text.Lower('device__name'), '-is_active', django.db.models.functions.text.Lower('name')], 'verbose_name_plural': '5. Sensors'},
        ),
        migrations.AlterField(
            model_name='device',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='site_plan',
            field=models.ImageField(blank=True, null=True, upload_to='site_plans/', validators=[sensors.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_type',
            field=models.CharField(choices=[('TEMP', 'Temperature'), ('HUM', 'Humidity'), ('PRESS', 'Pressure'), ('CO2', 'CO2'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
