# Generated by Django 5.1.7 on 2025-03-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0021_toastmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='site_plan_aspect_ratio',
            field=models.FloatField(default=1.333, help_text='Aspect ratio of the site plan (width/height)'),
        ),
    ]
