# Generated by Django 5.1.7 on 2025-03-08 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0022_place_site_plan_aspect_ratio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='site_plan_aspect_ratio',
        ),
        migrations.RemoveField(
            model_name='place',
            name='site_plan_scale',
        ),
        migrations.RemoveField(
            model_name='place',
            name='site_plan_x',
        ),
        migrations.RemoveField(
            model_name='place',
            name='site_plan_y',
        ),
    ]
