# Generated by Django 5.1.7 on 2025-03-08 23:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0023_remove_place_site_plan_aspect_ratio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='x_coord',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('50.00'), max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='y_coord',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('50.00'), max_digits=5, null=True),
        ),
    ]
