# Generated by Django 5.1.7 on 2025-03-09 13:11

import sensors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0024_alter_location_x_coord_alter_location_y_coord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='x_coord',
            new_name='x_pos',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='y_coord',
            new_name='y_pos',
        ),
        migrations.RemoveField(
            model_name='place',
            name='site_plan',
        ),
        migrations.AddField(
            model_name='place',
            name='siteplan_image',
            field=models.ImageField(blank=True, null=True, upload_to='siteplan_images/', validators=[sensors.models.validate_image_size]),
        ),
    ]
