# Generated by Django 5.1.7 on 2025-03-12 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0026_toastnotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToastReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='toastmessage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='toastnotification',
            name='read',
        ),
        migrations.AddField(
            model_name='toastnotification',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toast_notifications', to='sensors.place'),
        ),
        migrations.AlterField(
            model_name='device',
            name='is_active',
            field=models.BooleanField(default=True, help_text='inactive devices will be hidden by default'),
        ),
        migrations.AlterField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(default=True, help_text='inactive locations will be hidden by default'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='is_active',
            field=models.BooleanField(default=True, help_text='inactive sensors will be hidden by default'),
        ),
        migrations.AlterField(
            model_name='toastnotification',
            name='type',
            field=models.CharField(choices=[('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('info', 'Info'), ('danger', 'Danger')], max_length=20),
        ),
        migrations.AlterField(
            model_name='toastnotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toast_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='toastnotification',
            index=models.Index(fields=['user', '-created_at'], name='sensors_toa_user_id_0b5407_idx'),
        ),
        migrations.AddIndex(
            model_name='toastnotification',
            index=models.Index(fields=['place', '-created_at'], name='sensors_toa_place_i_e13562_idx'),
        ),
        migrations.AddIndex(
            model_name='toastnotification',
            index=models.Index(fields=['user', 'place', '-created_at'], name='sensors_toa_user_id_2fd531_idx'),
        ),
        migrations.AddField(
            model_name='toastreadstatus',
            name='toast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.toastnotification'),
        ),
        migrations.AddField(
            model_name='toastreadstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ToastMessage',
        ),
        migrations.AddIndex(
            model_name='toastreadstatus',
            index=models.Index(fields=['user', 'toast'], name='sensors_toa_user_id_a6864d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='toastreadstatus',
            unique_together={('user', 'toast')},
        ),
    ]
