# Generated by Django 5.1.7 on 2025-03-16 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0027_toastreadstatus_remove_toastmessage_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
