# Generated by Django 5.1.7 on 2025-03-25 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0028_alter_location_is_active_alter_sensor_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='data_type',
            field=models.CharField(choices=[('DIRECT', 'Direct'), ('INFLUX', 'InfluxDB')], default='DIRECT', max_length=10),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='influx_measurement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='influx_source',
            field=models.CharField(blank=True, choices=[('MAIN', 'Main InfluxDB'), ('SECONDARY', 'Secondary InfluxDB')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active Status'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_type',
            field=models.CharField(choices=[('TEMPERATURE', 'Temperature'), ('HUMIDITY', 'Humidity'), ('PRESSURE', 'Pressure'), ('LIGHT', 'Light'), ('SOUND', 'Sound'), ('MOTION', 'Motion'), ('CO2', 'Carbon Dioxide'), ('VOC', 'Volatile Organic Compounds'), ('PM25', 'Particulate Matter 2.5'), ('PM10', 'Particulate Matter 10'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='unit',
            field=models.CharField(choices=[('C', '°C'), ('F', '°F'), ('K', 'K'), ('RH', '%RH'), ('PA', 'Pa'), ('HPA', 'hPa'), ('LUX', 'lux'), ('DB', 'dB'), ('PPM', 'ppm'), ('PPB', 'ppb'), ('UGM3', 'μg/m³'), ('NONE', '(None)')], max_length=10),
        ),
    ]
