# Generated by Django 5.1.7 on 2025-07-04 11:47

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0029_alter_sensor_data_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['place', 'location', '-is_active', django.db.models.functions.text.Lower('name')], 'verbose_name_plural': '4. Devices'},
        ),
        migrations.AddField(
            model_name='device',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='sensors.place'),
        ),
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='sensors.location'),
        ),
    ]
