# Generated by Django 5.1.7 on 2025-07-04 12:42

from django.db import migrations

def populate_device_place_from_location(apps, schema_editor):
    """
    Populate the `place` field for existing `Device` instances
    based on their `location`.
    """
    Device = apps.get_model('sensors', 'Device')
    for device in Device.objects.filter(location__isnull=False, place__isnull=True):
        if device.location:
            device.place = device.location.place
            device.save()

class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0030_alter_device_options_device_place_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_device_place_from_location, migrations.RunPython.noop),
    ]
