# Generated by Django 5.1.7 on 2025-07-04 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0031_populate_device_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='device',
            name='device_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='sensors.place'),
        ),
    ]
