# Generated by Django 5.0.6 on 2024-07-16 13:28

from django.db import migrations
from django.db.models.functions import Lower


def convert_device_ids_to_lowercase(apps, schema_editor):
    """
    Update all existing Device objects to have a lowercase device_id.
    """
    Device = apps.get_model('sensors', 'Device')
    # Use the Lower function to perform the update at the database level
    # for efficiency. This avoids loading each object into memory.
    Device.objects.filter(device_id__isnull=False).update(device_id=Lower('device_id'))


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0032_remove_device_serial_number_device_device_id_and_more'),
    ]

    operations = [
        migrations.RunPython(convert_device_ids_to_lowercase, migrations.RunPython.noop),
    ]
