# Generated by Django 5.2.4 on 2025-07-15 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0033_lowercase_device_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='influxsource',
            old_name='read_token',
            new_name='token',
        ),
        migrations.RenameField(
            model_name='influxsource',
            old_name='server_dns',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='influxsource',
            name='server_port',
        ),
        migrations.RemoveField(
            model_name='influxsource',
            name='write_token',
        ),
        migrations.AddField(
            model_name='device',
            name='is_lorawan',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='influx_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensors', to='sensors.influxsource'),
        ),
    ]
