# Generated by Django 5.2.4 on 2025-07-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0034_rename_read_token_influxsource_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='is_lorawan',
            field=models.BooleanField(default=False, verbose_name='LoRaWAN Device'),
        ),
    ]
