# Generated by Django 5.2.4 on 2025-07-17 13:23

from django.db import migrations, models
from django.utils.text import slugify

def generate_unique_slugs(apps, schema_editor):
    Location = apps.get_model('sensors', 'Location')
    for location in Location.objects.all():
        if not location.slug:
            slug = slugify(location.name)
            unique_slug = slug
            counter = 1
            while Location.objects.filter(place=location.place, slug=unique_slug).exists():
                unique_slug = f'{slug}-{counter}'
                counter += 1
            location.slug = unique_slug
            location.save()

class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0035_alter_device_is_lorawan'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.RunPython(generate_unique_slugs, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('place', 'slug')},
        ),
    ]
