# Generated by Django 5.2.4 on 2025-07-20 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0036_location_slug_alter_location_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='influxsource',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='influx_sources', to='sensors.place'),
            preserve_default=False,
        ),
    ]
