# Generated by Django 5.2.4 on 2025-07-26 00:45

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0037_influxsource_place'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['location__place', 'location', '-is_active', django.db.models.functions.text.Lower('name')], 'verbose_name_plural': '4. Devices'},
        ),
        migrations.RemoveField(
            model_name='device',
            name='place',
        ),
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='sensors.devicetype'),
        ),
    ]
