# Generated by Django 5.2.4 on 2025-07-26 00:45

from django.db import migrations

def migrate_device_place_to_location(apps, schema_editor):
    """
    Migrates devices with a 'place' but no 'location' to a default "Unassigned" location for that place.
    """
    Device = apps.get_model('sensors', 'Device')
    Location = apps.get_model('sensors', 'Location')

    # Since 'place' is removed in a previous migration, we need to access it through the historical model
    # This is a bit of a trick to get the historical data
    db_alias = schema_editor.connection.alias
    
    # We can't query on the historical model directly, so we need to be a bit more creative
    # We'll get all devices that have a null location, and then get their historical place
    devices_to_migrate = Device.objects.using(db_alias).filter(location__isnull=True)

    for device in devices_to_migrate:
        # We need to get the historical version of the device to access the old 'place' field
        try:
            # This is not a direct way, but we can get the related place from the historical data
            # by looking at the state before the field was removed.
            # This is complex, and for this case, we'll assume a simpler approach will work.
            # We will try to get the 'place_id' directly from the database row.
            
            # This is a bit of a raw query, but it's the most reliable way to get the old data
            with schema_editor.connection.cursor() as cursor:
                cursor.execute("SELECT place_id FROM sensors_device WHERE id = %s", [device.id])
                row = cursor.fetchone()
                if row:
                    place_id = row[0]
                    if place_id:
                        # Get or create the "Unassigned Devices" location for the device's place
                        unassigned_location, created = Location.objects.using(db_alias).get_or_create(
                            place_id=place_id,
                            slug='unassigned-devices',
                            defaults={
                                'name': 'Unassigned Devices',
                                'is_active': False,
                                'description': 'Default location for devices that are not yet physically placed.'
                            }
                        )
                        
                        # Assign the device to this location
                        device.location = unassigned_location
                        device.save(update_fields=['location'])
        except Exception as e:
            # Handle cases where the place_id might not exist or other errors
            # For this migration, we'll just print a warning and continue
            print(f"Could not migrate device {device.id}: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0038_refactor_device_location_step1'),
    ]

    operations = [
        migrations.RunPython(migrate_device_place_to_location, migrations.RunPython.noop),
    ]
