# Generated by Django 5.2.4 on 2025-08-04 11:27

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0040_refactor_device_location_step3_schema'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['-is_active', django.db.models.functions.text.Lower('name')], 'verbose_name_plural': '4. Devices'},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'ordering': [django.db.models.functions.text.Lower('device__name'), '-is_active', django.db.models.functions.text.Lower('name')], 'verbose_name_plural': '5. Sensors'},
        ),
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='sensors.location'),
        ),
    ]
