# Generated by Django 5.2.4 on 2025-08-04 11:52

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0041_alter_device_options_alter_sensor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['location__place', 'location', '-is_active', django.db.models.functions.text.Lower('name')], 'verbose_name_plural': '4. Devices'},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'ordering': [django.db.models.functions.text.Lower('device__location__name'), django.db.models.functions.text.Lower('device__name'), '-is_active', django.db.models.functions.text.Lower('name')], 'verbose_name_plural': '5. Sensors'},
        ),
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='sensors.location'),
            preserve_default=False,
        ),
    ]
