# Generated by Django 5.2.4 on 2025-08-04 12:16

from django.db import migrations

def create_unassigned_locations(apps, schema_editor):
    Place = apps.get_model('sensors', 'Place')
    Location = apps.get_model('sensors', 'Location')
    for place in Place.objects.all():
        Location.objects.get_or_create(
            place=place,
            slug='unassigned-devices',
            defaults={
                'name': 'Unassigned Devices',
                'is_active': False,
                'description': 'Default location for devices that are not yet physically placed.'
            }
        )

class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0042_alter_device_options_alter_sensor_options_and_more'),
    ]

    operations = [
        migrations.RunPython(create_unassigned_locations),
    ]
