# Generated by Django 5.2.4 on 2025-08-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0043_create_unassigned_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
