# Generated by Django 5.2.4 on 2025-08-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0044_alter_device_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='graph_type',
            field=models.CharField(choices=[('LINE', 'Line Graph'), ('SCATTER', 'Scatter Plot')], default='SCATTER', max_length=20),
        ),
    ]
