# Generated by Django 5.2.4 on 2025-08-10 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0045_sensor_graph_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='sensor_type',
            new_name='sensor_type_old',
        ),
        migrations.RenameField(
            model_name='sensor',
            old_name='unit',
            new_name='unit_old',
        ),
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Sensor Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('symbol', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Units',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sensors.sensortype'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sensors.unit'),
        ),
    ]
