# Generated by Django 5.2.4 on 2025-08-10 12:32

from django.db import migrations

SENSOR_TYPES = [
    ('TEMPERATURE', 'Temperature'),
    ('HUMIDITY', 'Humidity'),
    ('PRESSURE', 'Pressure'),
    ('LIGHT', 'Light'),
    ('SOUND', 'Sound'),
    ('MOTION', 'Motion'),
    ('CO2', 'Carbon Dioxide'),
    ('VOC', 'Volatile Organic Compounds'),
    ('PM25', 'Particulate Matter 2.5'),
    ('PM10', 'Particulate Matter 10'),
    ('OTHER', 'Other'),
]
UNITS = [
    ('C', '°C'),
    ('F', '°F'),
    ('K', 'K'),
    ('RH', '%RH'),
    ('PA', 'Pa'),
    ('HPA', 'hPa'),
    ('LUX', 'lux'),
    ('DB', 'dB'),
    ('PPM', 'ppm'),
    ('PPB', 'ppb'),
    ('UGM3', 'μg/m³'),
    ('NONE', '(None)'),
]

def migrate_data(apps, schema_editor):
    SensorType = apps.get_model('sensors', 'SensorType')
    Unit = apps.get_model('sensors', 'Unit')
    Sensor = apps.get_model('sensors', 'Sensor')

    for code, name in SENSOR_TYPES:
        SensorType.objects.get_or_create(name=name)

    for symbol, name in UNITS:
        Unit.objects.get_or_create(symbol=symbol, defaults={'name': name})

    for sensor in Sensor.objects.all():
        if sensor.sensor_type_old:
            sensor_type_name = dict(SENSOR_TYPES).get(sensor.sensor_type_old)
            if sensor_type_name:
                sensor_type_obj = SensorType.objects.get(name=sensor_type_name)
                sensor.sensor_type = sensor_type_obj

        if sensor.unit_old:
            unit_obj = Unit.objects.filter(symbol=sensor.unit_old).first()
            if unit_obj:
                sensor.unit = unit_obj

        sensor.save()

class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0046_sensortype_unit_alter_sensor_sensor_type_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_data),
    ]
