# Generated by Django 5.2.4 on 2025-08-10 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0047_migrate_sensor_types_and_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='sensor_type_old',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='unit_old',
        ),
    ]
