# Generated by Django 5.2.4 on 2025-08-14 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0048_remove_old_sensor_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='data_type_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sensor',
            name='unit_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sensortype',
            name='default_data_type',
            field=models.CharField(blank=True, choices=[('DIRECT', 'Direct'), ('INFLUX', 'InfluxDB (Gauge)'), ('INFLUX_CUMULATIVE_RESET', 'InfluxDB (Cumulative, Resets)')], default='DIRECT', max_length=30),
        ),
        migrations.AddField(
            model_name='sensortype',
            name='default_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sensors.unit'),
        ),
        migrations.AddField(
            model_name='sensortype',
            name='max_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensortype',
            name='min_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='data_type',
            field=models.CharField(blank=True, choices=[('DIRECT', 'Direct'), ('INFLUX', 'InfluxDB (Gauge)'), ('INFLUX_CUMULATIVE_RESET', 'InfluxDB (Cumulative, Resets)')], default='DIRECT', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='graph_type',
            field=models.CharField(choices=[('LINE', 'Line Graph'), ('SCATTER', 'Scatter Plot'), ('BAR', 'Bar Graph')], default='SCATTER', max_length=20),
        ),
    ]
