# Generated by Django 5.2.4 on 2025-08-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0049_sensor_data_type_override_sensor_unit_override_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensortype',
            name='allow_override',
            field=models.BooleanField(default=False),
        ),
    ]
