# Generated by Django 5.2.4 on 2025-08-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0050_sensortype_allow_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensortype',
            name='decimal_places',
            field=models.PositiveIntegerField(blank=True, help_text='Number of decimal places to display for sensor readings.', null=True),
        ),
    ]
