# Generated by Django 5.2.5 on 2025-08-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0051_sensortype_decimal_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='max_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='max_value_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sensor',
            name='min_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='min_value_override',
            field=models.BooleanField(default=False),
        ),
    ]
