# Generated by Django 5.2.5 on 2025-10-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0052_add_min_max_value_overrides_to_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes for this device.', null=True),
        ),
    ]
