# Generated by Django 5.2.5 on 2025-10-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0053_add_notes_to_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_switchbot',
            field=models.BooleanField(default=False, help_text='Is this a SwitchBot device?'),
        ),
        migrations.AddField(
            model_name='device',
            name='switchbot_hub_device_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
