# Generated by Django 5.2.5 on 2025-10-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0054_device_is_switchbot_device_switchbot_hub_device_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='switchbot_hub_id',
            field=models.CharField(blank=True, help_text='The device ID of the SwitchBot Hub associated with this place.', max_length=100, null=True),
        ),
    ]
