# Generated by Django 4.2.19 on 2025-10-18 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0055_place_switchbot_hub_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='switchbot_hub_id',
        ),
    ]
