# Generated by Django 5.2.7 on 2025-10-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0056_remove_place_switchbot_hub_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='current_reading_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='current_reading_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='stale_threshold_override_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Override the default stale time from the sensor type, in seconds.', null=True),
        ),
        migrations.AddField(
            model_name='sensortype',
            name='default_stale_threshold_seconds',
            field=models.PositiveIntegerField(blank=True, default=300, help_text='Default stale time for this sensor type, in seconds. Default is 5 minutes.', null=True),
        ),
    ]
