# Generated by Django 5.2.7 on 2025-10-23 12:20

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0057_sensor_current_reading_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['location__place', 'location', '-is_active', django.db.models.functions.text.Lower('name')], 'verbose_name_plural': '3. Devices'},
        ),
        migrations.AlterModelOptions(
            name='devicetype',
            options={'ordering': ['name'], 'verbose_name_plural': '6. Device Types'},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'ordering': [django.db.models.functions.text.Lower('device__location__name'), django.db.models.functions.text.Lower('device__name'), '-is_active', django.db.models.functions.text.Lower('name')], 'verbose_name_plural': '4. Sensors'},
        ),
        migrations.AlterModelOptions(
            name='sensortype',
            options={'ordering': ['name'], 'verbose_name_plural': '7. Sensor Types'},
        ),
        migrations.AddField(
            model_name='sensortype',
            name='switchbot_api_key',
            field=models.CharField(blank=True, help_text="The key in the SwitchBot API response for this sensor type (e.g., 'temperature', 'leakState').", max_length=50, null=True),
        ),
    ]
