# Generated by Django 5.2.7 on 2025-10-28 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0058_alter_device_options_alter_devicetype_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensortype',
            name='switchbot_api_key',
        ),
    ]
