# Generated by Django 5.2.7 on 2025-10-29 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0059_remove_sensortype_switchbot_api_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='current_reading_timestamp',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='current_reading_value',
        ),
        migrations.AddField(
            model_name='sensor',
            name='cached_reading_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='cached_reading_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
