# Generated by Django 5.2.7 on 2025-10-29 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0060_rename_sensor_cached_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='last_checked_timestamp',
            field=models.DateTimeField(blank=True, help_text='The last time the application checked for a new value from the source.', null=True),
        ),
    ]
