# Generated by Django 5.2.8 on 2025-11-27 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0061_add_sensor_last_checked_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='value_boolean',
            field=models.BooleanField(blank=True, help_text='Boolean value for this reading, if applicable.', null=True),
        ),
    ]
