# Generated by Django 5.2.8 on 2025-11-27 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0062_sensorreading_value_boolean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='symbol',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
