# Generated by Django 5.2.8 on 2025-11-27 00:38

from django.db import migrations

def create_boolean_unit(apps, schema_editor):
    Unit = apps.get_model('sensors', 'Unit')
    if not Unit.objects.filter(name='Boolean').exists():
        Unit.objects.create(name='Boolean', symbol='')

def remove_boolean_unit(apps, schema_editor):
    Unit = apps.get_model('sensors', 'Unit')
    Unit.objects.filter(name='Boolean').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0063_alter_unit_symbol'),
    ]

    operations = [
        migrations.RunPython(create_boolean_unit, remove_boolean_unit),
    ]
