# Generated by Django 5.2.8 on 2025-11-27 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0064_create_boolean_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='default_influx_source',
            field=models.ForeignKey(blank=True, help_text="Default InfluxDB source for this place's sensors.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_places', to='sensors.influxsource'),
        ),
    ]
