# Generated by Django 5.2.8 on 2025-11-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0065_place_default_influx_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='symbol',
            field=models.CharField(max_length=10),
        ),
    ]
