# Generated by Django 5.2.8 on 2025-11-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0074_enforce_allow_override_water_detector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='graph_type',
            field=models.CharField(blank=True, choices=[('LINE', 'Line Graph'), ('SCATTER', 'Scatter Plot'), ('BAR', 'Bar Graph'), ('STEP', 'Step Graph (Alarm)'), ('ALARM_BAR', 'Alarm Bar Graph'), ('OVERLAY', 'Overlay Graph (Alarm)')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sensortype',
            name='default_graph_type',
            field=models.CharField(choices=[('LINE', 'Line Graph'), ('SCATTER', 'Scatter Plot'), ('BAR', 'Bar Graph'), ('STEP', 'Step Graph (Alarm)'), ('ALARM_BAR', 'Alarm Bar Graph'), ('OVERLAY', 'Overlay Graph (Alarm)')], default='SCATTER', max_length=20),
        ),
    ]
