# Generated by Django 5.2.8 on 2025-12-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0075_alter_sensor_graph_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='switchbot_enable',
            field=models.BooleanField(default=False, help_text='Enable SwitchBot integration for this place.'),
        ),
        migrations.AddField(
            model_name='place',
            name='switchbot_secret',
            field=models.CharField(blank=True, help_text='SwitchBot API Secret', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='switchbot_token',
            field=models.CharField(blank=True, help_text='SwitchBot API Token', max_length=255, null=True),
        ),
    ]
