# Generated by Django 5.2.8 on 2025-12-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0076_place_switchbot_enable_place_switchbot_secret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='switchbot_user_id',
            field=models.CharField(blank=True, help_text='SwitchBot User ID', max_length=255, null=True),
        ),
    ]
