# Generated by Django 5.2.8 on 2025-12-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0077_place_switchbot_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='collection_interval',
            field=models.PositiveIntegerField(blank=True, help_text='Polling interval in seconds for polled sensors (e.g., SwitchBot).', null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='switchbot_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='switchbot_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='switchbot_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
