# Generated by Django 5.2.8 on 2025-12-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0078_sensor_collection_interval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='data_type',
            field=models.CharField(blank=True, choices=[('DIRECT', 'Direct'), ('INFLUX', 'InfluxDB (Gauge)'), ('INFLUX_CUMULATIVE_RESET', 'InfluxDB (Cumulative, Resets)'), ('NONE', 'None')], default='DIRECT', max_length=30, null=True),
        ),
    ]
