# Generated by Django 5.2.8 on 2025-12-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0079_alter_sensor_data_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='graph_type',
            field=models.CharField(blank=True, choices=[('LINE', 'Line Graph'), ('SCATTER', 'Scatter Plot'), ('BAR', 'Bar Graph'), ('STEP', 'Step Graph')], default=None, max_length=20, null=True),
        ),
    ]
