# Generated by Django 5.2.8 on 2025-12-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0080_alter_sensor_graph_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='switchbot_hub_device_id',
        ),
        migrations.AddField(
            model_name='device',
            name='hub_id',
            field=models.CharField(blank=True, help_text='Identifier for the hub or bridge device, if any.', max_length=100, null=True),
        ),
    ]
