# Generated by Django 5.2.8 on 2025-12-02 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0081_remove_device_switchbot_hub_device_id_device_hub_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='switchbot_influx_source',
            field=models.ForeignKey(blank=True, help_text='InfluxDB source specifically for SwitchBot devices at this place.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='switchbot_for_places', to='sensors.influxsource'),
        ),
    ]
