# Generated by Django 5.2.8 on 2025-12-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0082_place_switchbot_influx_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='influx_field_name',
            field=models.CharField(blank=True, help_text='The field name in the InfluxDB measurement.', max_length=100, null=True),
        ),
    ]
