# Generated by Django 5.2.8 on 2025-12-03 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0083_add_influx_field_name_to_sensor'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeStampedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sensortype',
            name='default_graph_type',
        ),
        migrations.RemoveField(
            model_name='sensortype',
            name='default_unit',
        ),
        migrations.AddField(
            model_name='sensortype',
            name='graph_type',
            field=models.CharField(blank=True, choices=[('LINE', 'Line Graph'), ('SCATTER', 'Scatter Plot'), ('BAR', 'Bar Graph'), ('STEP', 'Step Graph')], default='LINE', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sensortype',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sensors.unit'),
        ),
        migrations.AlterField(
            model_name='sensortype',
            name='decimal_places',
            field=models.PositiveIntegerField(blank=True, default=2, null=True),
        ),
    ]
