# Generated by Django 5.2.8 on 2025-12-03 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0084_timestampedmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='collection_interval',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='stale_threshold_override_seconds',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='sensor',
            name='influx_tag_key',
            field=models.CharField(blank=True, help_text="The InfluxDB tag key to filter by (e.g., 'host', 'device_id').", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='stale_threshold_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Override the default stale threshold for this sensor (in seconds).', null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='cached_reading_timestamp',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='cached_reading_value',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='influx_field_name',
            field=models.CharField(blank=True, help_text='The specific field name within the InfluxDB measurement.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='influx_measurement',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='influx_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sensors.influxsource'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='last_checked_timestamp',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
