# Generated by Django 6.0 on 2025-12-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0085_add_influx_tag_key_to_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='influx_field_name',
            field=models.CharField(blank=True, help_text='Influx field name', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='influx_tag_key',
            field=models.CharField(blank=True, help_text='The InfluxDB tag key, e.g. host, device_id', max_length=100, null=True),
        ),
    ]
