# Generated by Django 6.0 on 2025-12-05 10:00

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('sensors', '0086_sensor_created_at_sensor_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InfluxSource',
            new_name='InfluxStore',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='default_influx_source',
            new_name='default_influx_store',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='switchbot_influx_source',
            new_name='switchbot_influx_store',
        ),
        migrations.RenameField(
            model_name='sensor',
            old_name='influx_source',
            new_name='influx_store',
        ),
    ]
