# Generated by Django 6.0 on 2025-12-05 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0087_remove_place_default_influx_source_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='influxstore',
            options={'verbose_name_plural': 'InfluxDB Stores'},
        ),
        migrations.AlterField(
            model_name='influxstore',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='influx_stores', to='sensors.place'),
        ),
        migrations.AlterField(
            model_name='place',
            name='default_influx_store',
            field=models.ForeignKey(blank=True, help_text="Default InfluxDB store for this place's sensors.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_places', to='sensors.influxstore'),
        ),
        migrations.AlterField(
            model_name='place',
            name='switchbot_influx_store',
            field=models.ForeignKey(blank=True, help_text='InfluxDB store specifically for SwitchBot devices at this place.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='switchbot_for_places', to='sensors.influxstore'),
        ),
    ]
