# Generated by Django 6.0 on 2025-12-05 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0088_alter_influxstore_options_alter_influxstore_place_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='influxstore',
            options={},
        ),
    ]
