# Generated by Django 6.0 on 2025-12-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0089_alter_influxstore_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, help_text='Additional device-specific data.'),
        ),
    ]
