# Generated by Django 6.0 on 2025-12-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0090_device_extra_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='glean_data',
            field=models.BooleanField(default=False, help_text='Set to true to capture the next full data payload from the device.'),
        ),
    ]
