# Generated by Django 6.0 on 2025-12-07 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0091_device_glean_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='glean_data',
            new_name='scrape_data',
        ),
    ]
