# Generated by Django 5.1.6 on 2025-12-07 15:14

from django.db import migrations

def create_switch_sensortype(apps, schema_editor):
    """
    Create a SensorType for Switches and a Unit for Boolean values.
    """
    SensorType = apps.get_model('sensors', 'SensorType')
    Unit = apps.get_model('sensors', 'Unit')
    db_alias = schema_editor.connection.alias

    # Create the Unit for Boolean values if it doesn't exist
    Unit.objects.using(db_alias).get_or_create(
        name='Boolean',
        defaults={
            'description': 'Represents a true/false state.',
            'symbol': '',
            'is_continuous': False
        }
    )

    # Create the SensorType for Switches
    SensorType.objects.using(db_alias).get_or_create(
        name='Switch',
        defaults={
            'description': 'A binary sensor that is either on or off.',
        }
    )


def reverse_switch_sensortype(apps, schema_editor):
    """
    Remove the SensorType and Unit created.
    """
    SensorType = apps.get_model('sensors', 'SensorType')
    Unit = apps.get_model('sensors', 'Unit')
    db_alias = schema_editor.connection.alias

    SensorType.objects.using(db_alias).filter(name='Switch').delete()
    # We will leave the Boolean unit as it may be useful for other types.


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0091_device_glean_data'),
    ]

    operations = [
        migrations.RunPython(create_switch_sensortype, reverse_code=reverse_switch_sensortype),
    ]
