# Generated by Django 6.0 on 2025-12-07 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0092_rename_glean_data_device_scrape_data'),
        ('sensors', '0093_add_switch_sensortype'),
    ]

    operations = [
    ]
