# Generated by Django 6.0 on 2025-12-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0094_merge_20251207_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(blank=True, help_text='Last time a webhook was received from this device.', null=True),
        ),
    ]
