# Generated by Django 6.0 on 2025-12-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0095_device_last_seen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='extra_data',
            new_name='scraped_data',
        ),
    ]
