# Generated by Django 6.0 on 2025-12-07 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0096_remove_device_extra_data_device_scraped_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='influxstore',
            unique_together={('place', 'name')},
        ),
        migrations.AlterField(
            model_name='device',
            name='scraped_data',
            field=models.JSONField(blank=True, default=dict, help_text='Additional device-specific data collected from webhooks or APIs.'),
        ),
        migrations.AlterField(
            model_name='influxstore',
            name='org',
            field=models.CharField(help_text='InfluxDB organization', max_length=100),
        ),
        migrations.AlterField(
            model_name='influxstore',
            name='token',
            field=models.CharField(help_text='InfluxDB API token', max_length=200),
        ),
        migrations.AlterField(
            model_name='influxstore',
            name='url',
            field=models.URLField(help_text='URL to InfluxDB instance'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='influx_field_name',
            field=models.CharField(blank=True, help_text="The field name in InfluxDB, e.g., 'value' or 'temperature'", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='influx_measurement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='influx_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensors', to='sensors.influxstore'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='influx_tag_key',
            field=models.CharField(blank=True, help_text="The key of the tag used to identify this sensor's data, e.g., 'sensor_id'", max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='influxstore',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='influxstore',
            name='updated_at',
        ),
    ]
