# Generated by Django 6.0 on 2025-12-08 01:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0097_alter_influxstore_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='z_pos',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5, null=True),
        ),
    ]
