# Generated by Django 6.0 on 2025-12-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0098_location_z_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='symbol',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
