# Generated by Django 6.0 on 2025-12-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0099_alter_unit_symbol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='data_type',
            new_name='data_store',
        ),
    ]
