# Generated by Django 6.0 on 2025-12-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0100_rename_datastore_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='last_checked_timestamp',
        ),
        migrations.AddField(
            model_name='sensor',
            name='last_cached_timestamp',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='data_store',
            field=models.CharField(blank=True, choices=[('DIRECT', 'Direct'), ('INFLUX', 'InfluxDB (Gauge)'), ('INFLUX_CUMULATIVE_RESET', 'InfluxDB (Cumulative, Resets)'), ('NONE', 'None')], default='DIRECT', max_length=30, null=True, verbose_name='Data Store'),
        ),
    ]
