# Generated by Django 6.0 on 2025-12-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0101_rename_last_checked_timestamp_to_last_cached'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='cached_reading_source',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
    ]
