# Generated by Django 6.0 on 2025-12-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0102_add_cached_reading_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='switchbot_sensor_name',
            field=models.CharField(blank=True, help_text='Original sensor name from SwitchBot API', max_length=100, null=True),
        ),
    ]
