# Generated by Django 6.0 on 2025-12-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0103_sensor_switchbot_sensor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='data_store',
            field=models.CharField(blank=True, choices=[('DIRECT', 'Direct'), ('INFLUX', 'InfluxDB (Gauge)'), ('INFLUX_CUMULATIVE_RESET', 'InfluxDB (Cumulative, Resets)'), ('NONE', 'None')], default='NONE', max_length=30, null=True, verbose_name='Data Store'),
        ),
    ]
